
CREATE DATABASE IF NOT EXISTS wtk CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE USER IF NOT EXISTS 'nkr'@'%' IDENTIFIED BY 'neeru@143';
GRANT ALL PRIVILEGES ON wtk.* TO 'nkr'@'%';
FLUSH PRIVILEGES;
